import { App } from "@/types/window";
import {
  FileText, Database, Activity, Radio, Terminal, Users, Wifi, Cpu, Mail, Globe,
  Music, Camera, Shield, MapPin, BookOpen, Zap, Wind, Calculator as CalcIcon,
  Lock, FileWarning, Grid3x3, ShoppingBag, StickyNote, Palette, Volume2,
  CloudRain, Clock as ClockIcon, Calendar, Newspaper, Key, HardDrive,
  FileArchive, Sheet, Presentation, Video, Image, Mic, Gamepad2, MessageSquare,
  Monitor, Package, Spade, Award, Coins, Dices, Timer, Cookie,
  Bell, History, Puzzle, Skull, ScanLine, Languages, BookOpenCheck, Globe2,
  MapPinned, Telescope, Beaker, Fingerprint, KeyRound,
} from "lucide-react";

export const createAppRegistry = (openAppById: (id: string) => void): App[] => [
  { id: "app-store", name: "App Store", icon: <ShoppingBag className="w-11 h-11" />, run: () => openAppById("app-store"), minimalInclude: true },
  { id: "explorer", name: "File Explorer", icon: <FileText className="w-11 h-11" />, run: () => openAppById("explorer"), minimalInclude: true },
  { id: "monitor", name: "System Monitor", icon: <Activity className="w-11 h-11" />, run: () => openAppById("monitor"), minimalInclude: true },
  { id: "personnel-center", name: "Personnel Center", icon: <Users className="w-11 h-11" />, run: () => openAppById("personnel-center"), standardInclude: true },
  { id: "logger", name: "Action Logger", icon: <Database className="w-11 h-11" />, run: () => openAppById("logger"), minimalInclude: true },
  { id: "network", name: "Network Scanner", icon: <Wifi className="w-11 h-11" />, run: () => openAppById("network"), standardInclude: true },
  { id: "terminal", name: "Terminal", icon: <Terminal className="w-11 h-11" />, run: () => openAppById("terminal"), minimalInclude: true },
  { id: "task-manager", name: "Task Manager", icon: <Cpu className="w-11 h-11" />, run: () => openAppById("task-manager"), minimalInclude: true },
  { id: "messages", name: "Messages", icon: <Mail className="w-11 h-11" />, run: () => openAppById("messages"), standardInclude: true },
  { id: "system-messages", name: "System Messages", icon: <Bell className="w-11 h-11" />, run: () => openAppById("system-messages"), standardInclude: true, searchAliases: ["warnings", "bans", "navi", "alerts", "notifications"] },
  { id: "notification-history", name: "Notification History", icon: <History className="w-11 h-11" />, run: () => openAppById("notification-history"), standardInclude: true, searchAliases: ["notifications", "history", "alerts", "log"] },
  { id: "incidents", name: "Incidents", icon: <FileWarning className="w-11 h-11" />, run: () => openAppById("incidents"), standardInclude: true },
  { id: "database", name: "Specimen DB", icon: <Database className="w-11 h-11" />, run: () => openAppById("database"), standardInclude: true },
  { id: "browser", name: "Browser", icon: <Globe className="w-11 h-11" />, run: () => openAppById("browser"), minimalInclude: true },
  { id: "audio-logs", name: "Audio Logs", icon: <Music className="w-11 h-11" />, run: () => openAppById("audio-logs") },
  { id: "cameras", name: "Security Cameras", icon: <Camera className="w-11 h-11" />, run: () => openAppById("cameras"), standardInclude: true },
  { id: "protocols", name: "Emergency Protocols", icon: <Shield className="w-11 h-11" />, run: () => openAppById("protocols"), standardInclude: true },
  { id: "map", name: "Facility Map", icon: <MapPin className="w-11 h-11" />, run: () => openAppById("map"), standardInclude: true },
  { id: "research", name: "Research Notes", icon: <BookOpen className="w-11 h-11" />, run: () => openAppById("research") },
  { id: "power", name: "Power Grid", icon: <Zap className="w-11 h-11" />, run: () => openAppById("power") },
  { id: "containment", name: "Containment", icon: <Lock className="w-11 h-11" />, run: () => openAppById("containment") },
  { id: "environment", name: "Environment", icon: <Wind className="w-11 h-11" />, run: () => openAppById("environment") },
  { id: "calculator", name: "Calculator", icon: <CalcIcon className="w-11 h-11" />, run: () => openAppById("calculator"), minimalInclude: true },
  { id: "planner", name: "Facility Planner", icon: <Grid3x3 className="w-11 h-11" />, run: () => openAppById("planner"), standardInclude: true },
  { id: "computer-management", name: "Computer Mgmt", icon: <Monitor className="w-11 h-11" />, run: () => openAppById("computer-management"), standardInclude: true },
  { id: "signal-interceptor", name: "Signal Interceptor", icon: <Radio className="w-11 h-11" />, run: () => openAppById("signal-interceptor"), standardInclude: true },
  { id: "plugin-store", name: "Plugin Store", icon: <Puzzle className="w-11 h-11" />, run: () => openAppById("plugin-store"), minimalInclude: true },
  { id: "crash-app", name: "System Crash", icon: <Skull className="w-11 h-11" />, run: () => openAppById("crash-app") },
  { id: "settings", name: "Settings", icon: <Zap className="w-11 h-11" />, run: () => openAppById("settings"), minimalInclude: true },
  { id: "file-reader", name: "File Reader", icon: <FileText className="w-11 h-11" />, run: () => openAppById("file-reader"), standardInclude: true },
  // Downloadable Apps
  { id: "notepad", name: "Notepad", icon: <StickyNote className="w-11 h-11" />, run: () => openAppById("notepad"), downloadable: true },
  { id: "paint", name: "Paint Tool", icon: <Palette className="w-11 h-11" />, run: () => openAppById("paint"), downloadable: true },
  { id: "music-player", name: "Media Player", icon: <Volume2 className="w-11 h-11" />, run: () => openAppById("music-player"), downloadable: true },
  { id: "weather", name: "Weather Monitor", icon: <CloudRain className="w-11 h-11" />, run: () => openAppById("weather"), downloadable: true },
  { id: "clock", name: "World Clock", icon: <ClockIcon className="w-11 h-11" />, run: () => openAppById("clock"), downloadable: true },
  { id: "calendar", name: "Event Calendar", icon: <Calendar className="w-11 h-11" />, run: () => openAppById("calendar"), downloadable: true },
  { id: "notes", name: "Advanced Notes", icon: <Newspaper className="w-11 h-11" />, run: () => openAppById("notes"), downloadable: true },
  { id: "vpn", name: "Secure VPN", icon: <Shield className="w-11 h-11" />, run: () => openAppById("vpn"), downloadable: true },
  { id: "firewall", name: "Network Firewall", icon: <Shield className="w-11 h-11" />, run: () => openAppById("firewall"), downloadable: true },
  { id: "antivirus", name: "Virus Scanner", icon: <Shield className="w-11 h-11" />, run: () => openAppById("antivirus"), downloadable: true },
  { id: "backup", name: "Data Backup", icon: <HardDrive className="w-11 h-11" />, run: () => openAppById("backup"), downloadable: true },
  { id: "compression", name: "File Compressor", icon: <FileArchive className="w-11 h-11" />, run: () => openAppById("compression"), downloadable: true },
  { id: "pdf-reader", name: "PDF Viewer", icon: <PdfIcon className="w-11 h-11" />, run: () => openAppById("pdf-reader"), downloadable: true },
  { id: "spreadsheet", name: "Data Sheets", icon: <Sheet className="w-11 h-11" />, run: () => openAppById("spreadsheet"), downloadable: true },
  { id: "presentation", name: "Slide Maker", icon: <Presentation className="w-11 h-11" />, run: () => openAppById("presentation"), downloadable: true },
  { id: "video-editor", name: "Video Editor", icon: <Video className="w-11 h-11" />, run: () => openAppById("video-editor"), downloadable: true },
  { id: "image-viewer", name: "Photo Gallery", icon: <Image className="w-11 h-11" />, run: () => openAppById("image-viewer"), downloadable: true },
  { id: "audio-editor", name: "Sound Editor", icon: <Mic className="w-11 h-11" />, run: () => openAppById("audio-editor"), downloadable: true },
  { id: "game-center", name: "Game Hub", icon: <Gamepad2 className="w-11 h-11" />, run: () => openAppById("game-center"), downloadable: true },
  { id: "containment-game", name: "Containment Breach", icon: <Skull className="w-11 h-11" />, run: () => openAppById("containment-game"), downloadable: true },
  { id: "ucg", name: "Untitled Card Game", icon: <Spade className="w-11 h-11" />, run: () => openAppById("ucg"), downloadable: true, searchAliases: ["UCG", "21", "twenty one", "blackjack", "card game"] },
  { id: "shop", name: "Shop", icon: <Coins className="w-11 h-11" />, run: () => openAppById("shop"), downloadable: true, searchAliases: ["store", "kroner", "buy", "themes", "titles"] },
  { id: "certificate-viewer", name: "Certificate Viewer", icon: <Award className="w-11 h-11" />, run: () => openAppById("certificate-viewer"), downloadable: true, searchAliases: ["certificates", "awards", "battlepass", "achievements"] },
  { id: "dice-roller", name: "Dice Roller", icon: <Dices className="w-11 h-11" />, run: () => openAppById("dice-roller"), downloadable: true, searchAliases: ["dice", "d20", "tabletop", "random", "roll"] },
  { id: "reaction-test", name: "Reaction Test", icon: <Timer className="w-11 h-11" />, run: () => openAppById("reaction-test"), downloadable: true, searchAliases: ["reflex", "speed", "reaction", "test"] },
  { id: "fortune", name: "Fortune Cookie", icon: <Cookie className="w-11 h-11" />, run: () => openAppById("fortune"), downloadable: true, searchAliases: ["fortune", "luck", "prediction", "cookie"] },
  { id: "toaster-simulator", name: "Toaster Simulator", icon: <Zap className="w-11 h-11" />, run: () => openAppById("toaster-simulator"), downloadable: true, searchAliases: ["toaster", "toast", "bread", "kitchen"] },
  { id: "chat", name: "Instant Chat", icon: <MessageSquare className="w-11 h-11" />, run: () => openAppById("chat"), downloadable: true },
  { id: "video-call", name: "Video Conference", icon: <Video className="w-11 h-11" />, run: () => openAppById("video-call"), downloadable: true },
  { id: "email-client", name: "Mail Client Pro", icon: <Mail className="w-11 h-11" />, run: () => openAppById("email-client"), downloadable: true },
  { id: "ftp", name: "FTP Manager", icon: <FileText className="w-11 h-11" />, run: () => openAppById("ftp"), downloadable: true },
  { id: "ssh", name: "SSH Terminal", icon: <Terminal className="w-11 h-11" />, run: () => openAppById("ssh"), downloadable: true },
  { id: "packet-analyzer", name: "Packet Sniffer", icon: <Wifi className="w-11 h-11" />, run: () => openAppById("packet-analyzer"), downloadable: true },
  { id: "disk-manager", name: "Disk Utility", icon: <HardDrive className="w-11 h-11" />, run: () => openAppById("disk-manager"), downloadable: true },
  { id: "registry", name: "Registry Editor", icon: <Key className="w-11 h-11" />, run: () => openAppById("registry"), downloadable: true },
  { id: "performance", name: "Performance Analyzer", icon: <Activity className="w-11 h-11" />, run: () => openAppById("performance"), downloadable: true },
  { id: "scanner", name: "Document Scanner", icon: <ScanLine className="w-11 h-11" />, run: () => openAppById("scanner"), downloadable: true },
  { id: "translator", name: "Language Translator", icon: <Languages className="w-11 h-11" />, run: () => openAppById("translator"), downloadable: true },
  { id: "dictionary", name: "Digital Dictionary", icon: <BookOpenCheck className="w-11 h-11" />, run: () => openAppById("dictionary"), downloadable: true },
  { id: "encyclopedia", name: "Encyclopedia", icon: <Globe2 className="w-11 h-11" />, run: () => openAppById("encyclopedia"), downloadable: true },
  { id: "map-viewer", name: "Map Navigator", icon: <MapPinned className="w-11 h-11" />, run: () => openAppById("map-viewer"), downloadable: true },
  { id: "gps", name: "GPS Tracker", icon: <MapPin className="w-11 h-11" />, run: () => openAppById("gps"), downloadable: true },
  { id: "astronomy", name: "Star Chart", icon: <Telescope className="w-11 h-11" />, run: () => openAppById("astronomy"), downloadable: true },
  { id: "chemistry", name: "Chemistry Lab", icon: <Beaker className="w-11 h-11" />, run: () => openAppById("chemistry"), downloadable: true },
  { id: "physics", name: "Physics Simulator", icon: <CalcIcon className="w-11 h-11" />, run: () => openAppById("physics"), downloadable: true },
  { id: "biometric", name: "Biometric Scanner", icon: <Fingerprint className="w-11 h-11" />, run: () => openAppById("biometric"), downloadable: true },
  { id: "encryption", name: "File Encryptor", icon: <Lock className="w-11 h-11" />, run: () => openAppById("encryption"), downloadable: true },
  { id: "password-manager", name: "Password Vault", icon: <KeyRound className="w-11 h-11" />, run: () => openAppById("password-manager"), downloadable: true },
  { id: "img-editor", name: ".Img Editor", icon: <FileArchive className="w-11 h-11" />, run: () => openAppById("img-editor"), downloadable: true },
  { id: "account-settings", name: "Account Settings", icon: <Users className="w-11 h-11" />, run: () => openAppById("account-settings"), minimalInclude: true },
  { id: "uur-manager", name: "UUR Manager", icon: <Package className="w-11 h-11" />, run: () => openAppById("uur-manager"), standardInclude: true },
];
