project_id = "oukxkpihsyikamzldiek"

[functions.admin-actions]
verify_jwt = false

[functions.navi-autonomous]
verify_jwt = false

[functions.navi-ai]
verify_jwt = false

[functions.send-appeal]
verify_jwt = false
